meu_site/enquete/urls.py
from django.urls import path, include 
from . import views 

app_name = 'enquete'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

meu_site/meu_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquete/', include('enquete.urls')),
]

meu_site/enquete/models.py
from django.db import models
from django.utils import timezone
from datetime import *


# Create your models here.
class Question (models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days =1)
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

meu_site/enquete/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import Question

# Create your views here.
def index (request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render (request,'enquete/index.html',context)


def vote (request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return render (request, 'enquete/vote.html', {
            'question':question,
            'error message':'você não selecionou um resposta ',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('enquete:results', args= (question_id,)))

        

def results (request, question_id):
    question = Question(pk =question_id)
    return render (request, 'enquete/results.html',{'question':question})


meu_site/enquete/templates/enquete/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <html lang="pt-br">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Enquete da html</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <p> teste  do git </p>
        <p> teste  do git ignore </p>
            {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list%}
                    <li><a href="{% url 'enquete:vote' question.id %}">{{question.question_text}}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <p> Sem enquetes liberadas</p>
            {% endif %}
        <script src="" async defer></script>
    </body>
</html>

meu_site/enquete/templates/enquete/results.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <html lang="pt-br">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Resultado dda enquete</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <h1>{{ question.question_text }}</h1>
        <ul>
            
            {% for choice  in question.choice_set.all %}
                <li> {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize }}</li>
            {% endfor %}         
        </ul>

        <a href="{% url 'enquete:vote' question.id %}">Vote novamente</a>
        <a href="{% url 'enquete:index' %}">ver outra enquete</a>
        <script src="" async defer></script>
    </body>
</html>

meu_site/enquete/templates/enquete/vote.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <html lang="pt-br">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Vote na enquete</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

<form action="{% url 'enquete:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
        <script src="" async defer></script>
    </body>
</html>